# docker/apache/Dockerfile
FROM httpd:2.4.51

COPY horbola-commerce.apache.conf /usr/local/apache2/conf/horbola-commerce.apache.conf

RUN echo "Include /usr/local/apache2/conf/horbola-commerce.apache.conf" \
    >> /usr/local/apache2/conf/httpd.conf